### PR TITLE
Adds VS2022 support

### LINKED ISSUE #2: VS2022 Support
Can you update the extension for VS2022?

### PR DESCRIPTION
**Pull request by CaffeineDaemon**
Fixes #2 

Followed the [VS2022 plugin migration guide](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022).

Successfully tested with Visual Studio Enterprise 17.2.2 and Visual Studio Enterprise 17.3 Preview 1.

### CODE REVIEW

**Comment by pavel-agarkov** [comment]
Thank you for your work.
Do I need any additional tools to work with this type of projects?
Currently I cannot open the solution neither in VS19 nor in VS22

### VS19 error:
```
The imported project "C:\Projects\VS\Extensions\RemoteDebugLauncherExtension\RemoteDebugLauncherShared\RemoteDebugLauncherShared.projitems" was not found. Confirm that the expression in the Import declaration "..\RemoteDebugLauncherShared\RemoteDebugLauncherShared.projitems" is correct, and that the file exists on disk.  C:\Projects\VS\Extensions\RemoteDebugLauncherExtension\RemoteDebugLauncher\RemoteDebugLauncher.csproj
```

### VS22 error:
```
The imported project "C:\Projects\VS\Extensions\RemoteDebugLauncherExtension\RemoteDebugLauncherShared\RemoteDebugLauncherShared.projitems" was not found. Confirm that the expression in the Import declaration "..\RemoteDebugLauncherShared\RemoteDebugLauncherShared.projitems" is correct, and that the file exists on disk.  C:\Projects\VS\Extensions\RemoteDebugLauncherExtension\RemoteDebugLauncher2022\RemoteDebugLauncher2022.csproj
```

Probably RemoteDebugLauncherShared.projitems is missing in the pull request.

**Comment by CaffeineDaemon** [comment]
You are right, i somehow forgot to commit that file. I'll fix this immediatly.

**Comment by pavel-agarkov** [comment]
I've published a new extension in preview mode
https://marketplace.visualstudio.com/items?itemName=xpasza.RemoteDebugLauncher22
Please take a look

**Comment by CaffeineDaemon** [comment]
I tried to open the link, but after signing in it only shows "We're sorry, the page you requested cannot be found!". Do i need any special permissions to access the preview release?

**Comment by pavel-agarkov** [comment]
I will try it out with my colleagues and let you know.
Thank you.

**Comment by pavel-agarkov** [comment]
I've made it a public preview.
Sorry it took me so long.

**Comment by CaffeineDaemon** [comment]
I had some colleagues install and test the preview version on their machines and no issues so far. What is your plan on merging and releasing?

**Pull request merged**
